# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f28c475e7c0e2da57e06813271b2f24efb1575835e8aa9cfb43668ae8c37206ce59daa8adefcd008a52562cf9d49ad1dca91c0eb5475c0d85cdd9411de272aa

test:
  secret_key_base: 16047cbf7a0bccdd3b8eeefbdc06511314b90b782dc0e62f216d0e339bde0dc4820f82e4807c59ed6aaee3ab17b193413e09de43fb1b952ef8e80dd93a07b71c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
